export const LOAD_TASKS_SUCCESS = 'LOAD_TASKS_SUCCESS';

export const LOAD_DASHBOARDS_START = 'LOAD_DASHBOARDS_START';
export const LOAD_DASHBOARDS_SUCCESS = 'LOAD_DASHBOARDS_SUCCESS';
export const LOAD_DASHBOARDS_ERROR = 'LOAD_DASHBOARDS_ERROR';

export const LOAD_DASHBOARD_START = 'LOAD_DASHBOARD_START';
export const LOAD_DASHBOARD_SUCCESS = 'LOAD_DASHBOARD_SUCCESS';
export const LOAD_DASHBOARD_ERROR = 'LOAD_DASHBOARD_ERROR';
export const RESET_DASHBOARD = 'RESET_DASHBOARD';

export const SAVE_DASHBOARD_START = 'SAVE_DASHBOARD_START';
export const SAVE_DASHBOARD_SUCCESS = 'SAVE_DASHBOARD_SUCCESS';
export const SAVE_DASHBOARD_ERROR = 'SAVE_DASHBOARD_ERROR';
export const UPDATE_DASHBOARD_SUCCESS = 'UPDATE_DASHBOARD_SUCCESS';
export const DELETE_DASHBOARD_OPTIMISTIC = 'DELETE_DASHBOARD_OPTIMISTIC';
export const DELETE_DASHBOARD_ERROR = 'DELETE_DASHBOARD_ERROR';
